name: WolvenKit Console Linux
description: Execute WolvenKit commands
author: Clement-Z4RM

inputs:
  command:
    description: The command to run in the Docker
    required: true

runs:
  using: docker
  image: ghcr.io://clement-z4rm/wolvenkit-consolelinux:v0.1.4
  env:
    COMMAND: ${{ inputs.command }}
  entrypoint: "entrypoint.sh"
