name: WolvenKit Console Linux
description: Execute WolvenKit commands
author: Clement-Z4RM

inputs:
  arguments:
    description: The arguments to send to WolvenKit command
    required: true

runs:
  using: docker
  image: docker://ghcr.io/clement-z4rm/wolvenkit-consolelinux:v0.1.8
  env:
    ARGUMENTS: ${{ inputs.arguments }}
  entrypoint: "/App/entrypoint.sh"
